[nixpacks]
runtime = "nodejs"

[env]
PORT = "3000"
KLAVIYO_API_KEY = "pk_a4c897e1716dae826c47517a20f80beebf"
KLAVIYO_COVERED_LIST = "W59Gm7"
KLAVIYO_NOT_COVERED_LIST = "UQBibj"

[dependencies]
nodejs = "20.10.0"